import { useState } from 'react';
import styles from '@src/styles/Home.module.css';
import Head from 'next/head';
import Link from 'next/link';

export default function Busca() {
  const [movies, setMovies] = useState([]);
  const [searchText, setSearchText] = useState('');

  const handleSearch = async () => {
    if (searchText.trim().length > 0) {
      const result = await fetch(
        `http://localhost:3000/api/search?movie=${searchText}`,
      );

      const json = await result.json();
      setMovies(json.movie);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Busca</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Busca</h1>
        <input
          value={searchText}
          type="text"
          onChange={(e) => setSearchText(e.target.value)}
        />
        <button onClick={handleSearch}>Buscar</button>
        <hr />
        <ul style={{ listStyle: 'none', margin: '0px' }}>
          {movies.map((movie) => (
            <li
              style={{
                listStyle: 'none',
                margin: '20px',
                display: 'inline-block',
                textAlign: 'center',
                cursor: 'pointer',
              }}
              key={Math.random()}
            >
              <Link href={`/movie/${movie.id}`}>
                <div>
                  <img
                    src={`https://image.tmdb.org/t/p/original${movie.poster_path}`}
                    height={220}
                    width={150}
                  />
                  <p style={{ color: 'black', width: '150px' }}>
                    {movie.title}
                  </p>
                </div>
              </Link>
            </li>
          ))}
        </ul>
      </main>
    </div>
  );
}
