import Head from 'next/head';
import Link from 'next/link';
import styles from '@src/styles/Home.module.css';

export default function Home({ list }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nextmovies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Filmes em destaque ⭐</h1>
        <Link href={`/busca`}>
          <p class={styles.customVariables}>Ir para a Busca</p>
        </Link>
      </main>
      <ul
        style={{
          display: 'flex',
          overflow: 'auto',
          background: 'linear-gradient(to right, #0f2027, #203a43, #2c5364)',
        }}
      >
        {list.map((item) => (
          <li
            key={Math.random() + item.id}
            style={{
              display: 'inline',
              minHeight: '300px',
              padding: '5px',
            }}
          >
            <Link href={`movie/${item.id}`}>
              <div className={styles.card}>
                <img
                  src={`https://image.tmdb.org/t/p/original${item.poster_path}`}
                  width={150}
                  height={150}
                />
                <p>{item.title}</p>
              </div>
            </Link>
          </li>
        ))}
      </ul>
    </div>
  );
}

export async function getServerSideProps() {
  const res = await fetch('http://localhost:3000/api/trending');
  const json = await res.json();

  return {
    props: {
      list: json.list,
    },
  };
}
