import Head from 'next/head';
import Link from 'next/link';
import styles from '@src/styles/Home.module.css';

export default function Movie({ info }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nextmovies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Filme: {info.title} 😍</h1>
        <p>Nota: {info.vote_average}</p>
        <p>{info.overview}</p>
        <img
          src={`https://image.tmdb.org/t/p/original${info.backdrop_path}`}
          width={400}
        />
        <Link href={`/busca`}>
          <p className={styles.customVariables}>Ir para a Busca</p>
        </Link>
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const { id } = context.params;

  const res = await fetch(`http://localhost:3000/api/movie/${id}`);
  const json = await res.json();

  if (!json) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      info: json.info,
    },
  };
}
